=encoding utf8

=head1 NAME

Pod::Perl5

=head1 VERSION

0.02

=head1 TODO

=over 2

=item * be able to parse inline POD (Pod mixed with code)

=item * enable formatting codes within formatting codes

=back

=head1 DESCRIPTION

This is a Perl6 module for parsing Perl 5 pod. The grammar for this module lives at C<Pod::Perl5::Grammar>.

The parser can parse *.pod files and supports all pod syntax. See L</TODO> for remaining issues.

=head1 SYNOPSIS

  use Pod::Perl5;

  my $match = Pod::Perl5.parse_file('/some.pod');
  my $match = Pod::Perl5::parse_string($pod);


=head2 INSTALL

Requires panda and Perl 6:

  $ clone https://github.com/dnmfarrell/Pod-Perl5.git
  $ cd Pod-Perl5
  $ panda install ./

=head1 TESTING

The parser has a decent test suite. You'll need Perl 5 and Perl 6 installed to run it with:

  $ prove --exec perl6 -r

Or run individual test files with Perl 6:

  $ perl6 t/01_basic.t

=head1 AUTHOR

David Farrell (C) 2015

=head1 LICENSE

FreeBSD, see LICENSE file

=head1 SEE ALSO

L<perlpod documentation|http://perldoc.perl.org/perlpod.html>

