=head1 NAME

Pod::Perl5

=head1 VERSION

0.01

=head1 DESCRIPTION

This is a Perl6 module for parsing Perl 5 pod. The grammar for this module lives at C<Pod::Perl5::Grammar>.

=head1 SYNOPSIS

  use Pod::Perl5;

  my $match = Pod::Perl5.parse_file('/some.pod');

  # or:

  my $match = Pod::Perl5::parse_string($pod);

=head1 AUTHOR

David Farrell (C) 2015

=head1 LICENSE

FreeBSD, see LICENSE file

=head1 SEE ALSO

L<perlpod documentation|http://perldoc.perl.org/perlpod.html>

