=head1 NAME

example-perl5.pod

=head1 DESCRIPTION

This is an example pod file written in Perl 5 style pod (as opposed to Perl 6 style).
The grammar for this module lives at L<Pod::Perl5::Grammar>.

=head1 SYNOPSIS

  use Pod::Perl5;

  my $match = Pod::Perl5.parse_file('/some.pod');

  # or:

  my $match = Pod::Perl5::parse_string($pod);

=head1 AUTHOR

David Farrell (C) 2015


=head1 LICENSE

FreeBSD, see LICENSE file

